server:
port: 8080

spring:
  datasource:
    url: jdbc:mysql://139.196.10.146:3306/you_can_pass?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234

mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
    - classpath:mybatis/dao/*.xml

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

